// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoH7Iq6k2jEFz1BLLU6P1XIMilno9iOgc',
    appId: '1:413370429911:android:5c6fb3c156130de473db92',
    messagingSenderId: '413370429911',
    projectId: 'cw6-taskmanager',
    storageBucket: 'cw6-taskmanager.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTctm68izDZz9ihm6V0KERdx2E-7pNyIA',
    appId: '1:413370429911:web:6e2d7935fffbb11573db92',
    messagingSenderId: '413370429911',
    projectId: 'cw6-taskmanager',
    authDomain: 'cw6-taskmanager.firebaseapp.com',
    storageBucket: 'cw6-taskmanager.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTctm68izDZz9ihm6V0KERdx2E-7pNyIA',
    appId: '1:413370429911:web:3b71438129c0c49b73db92',
    messagingSenderId: '413370429911',
    projectId: 'cw6-taskmanager',
    authDomain: 'cw6-taskmanager.firebaseapp.com',
    storageBucket: 'cw6-taskmanager.firebasestorage.app',
  );

}